import { useState, useEffect } from 'react'
import { SquidIcon } from './SquidIcon'

interface P4Client {
  name: string
  root: string
  description: string
}

interface P4Depot {
  depot: string
  type: string
  map: string
  description: string
}

interface P4Stream {
  stream: string
  name: string
  parent: string
  type: string
  depotName: string
  description: string
}

interface ClientSelectorProps {
  onClientSelected: (client: string) => void
}

export function ClientSelector({ onClientSelected }: ClientSelectorProps) {
  const [clients, setClients] = useState<P4Client[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  
  // Create Mode State
  const [isCreateMode, setCreateMode] = useState(false)
  const [isCreating, setIsCreating] = useState(false)
  
  // Auto-generation State
  const [depots, setDepots] = useState<P4Depot[]>([])
  const [streams, setStreams] = useState<P4Stream[]>([])
  const [loadingStreams, setLoadingStreams] = useState(false)
  const [selectedDepot, setSelectedDepot] = useState('')
  const [selectedStream, setSelectedStream] = useState<P4Stream | null>(null)
  const [streamSearch, setStreamSearch] = useState('')
  
  const [prefix, setPrefix] = useState(() => localStorage.getItem('p4_client_prefix') || 'hoh_haein')
  const [rootBase, setRootBase] = useState(() => localStorage.getItem('p4_client_root_base') || 'C:\\Perforce')

  // Form State
  const [newName, setNewName] = useState('')
  const [newRoot, setNewRoot] = useState('')
  const [description, setDescription] = useState('')
  
  // Options
  const [optCompress, setOptCompress] = useState(true)
  const [optRmdir, setOptRmdir] = useState(true)
  const [optWritable, setOptWritable] = useState(true) // Client Type: Writable (allwrite) vs Read-only (noallwrite)
  const [optBackup, setOptBackup] = useState(true) // Backup enable
  const [submitOption, setSubmitOption] = useState('submitunchanged') // On submit
  
  useEffect(() => {
    loadClients()
  }, [])

  useEffect(() => {
    if (isCreateMode) {
      loadDepots()
    }
  }, [isCreateMode])

  useEffect(() => {
    localStorage.setItem('p4_client_prefix', prefix)
    updateAutoGeneratedFields(selectedStream, prefix, rootBase)
  }, [prefix])

  useEffect(() => {
    localStorage.setItem('p4_client_root_base', rootBase)
    updateAutoGeneratedFields(selectedStream, prefix, rootBase)
  }, [rootBase])

  useEffect(() => {
    updateAutoGeneratedFields(selectedStream, prefix, rootBase)
  }, [selectedStream])

  const updateAutoGeneratedFields = (stream: P4Stream | null, pfx: string, base: string) => {
    if (!stream) return

    // Use stream path leaf as the name for workspace generation, as it's often more specific/expected
    const streamLeaf = stream.stream.split('/').pop() || stream.name
    const generatedName = `${pfx}_${streamLeaf}`
    setNewName(generatedName)
    
    // Ensure base ends with backslash if not empty, handling Windows paths
    const cleanBase = base.endsWith('\\') || base.endsWith('/') ? base : `${base}\\`
    setNewRoot(`${cleanBase}${generatedName}`)
  }

  const loadClients = async () => {
    try {
      setLoading(true)
      const clientList = await window.p4.getClients()
      setClients(clientList)
      setError(null)
    } catch (err: any) {
      setError(err.message)
    } finally {
      setLoading(false)
    }
  }

  const loadDepots = async () => {
    try {
      const depotList = await window.p4.getDepots()
      setDepots(depotList)
      if (depotList.length > 0 && !selectedDepot) {
        // Optional: Select first depot? Or wait for user
        // setSelectedDepot(depotList[0].depot)
      }
    } catch (err) {
      console.error('Failed to load depots', err)
    }
  }

  const handleDepotChange = async (depot: string) => {
    setSelectedDepot(depot)
    setStreams([])
    setSelectedStream(null)
    setStreamSearch('') // Reset search on depot change
    
    if (!depot) return

    setLoadingStreams(true)
    try {
      const streamList = await window.p4.getStreams(depot)
      setStreams(streamList)
    } catch (err) {
      console.error('Failed to load streams', err)
    } finally {
      setLoadingStreams(false)
    }
  }

  const selectClient = async (clientName: string) => {
    await window.p4.setClient(clientName)
    onClientSelected(clientName)
  }

  const handleNameChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const val = e.target.value
    setNewName(val)
    // Update root based on rootBase + new name
    const cleanBase = rootBase.endsWith('\\') || rootBase.endsWith('/') ? rootBase : `${rootBase}\\`
    setNewRoot(`${cleanBase}${val}`)
  }

  const handleBrowseRoot = async () => {
    try {
      const path = await window.dialog.openDirectory()
      if (path) {
        setNewRoot(path)
        // Optionally update rootBase if we want to remember this location for next time
        // But extracting "base" from a full path is tricky without knowing the desired workspace name part.
        // For now, just setting the specific root is enough.
      }
    } catch (err) {
      console.error('Failed to open directory dialog', err)
    }
  }

  const handleCreate = async () => {
    if (!newName.trim() || !newRoot.trim()) {
      setError('Workspace name and root are required')
      return
    }

    setIsCreating(true)
    setError(null)

    try {
      // Construct options string
      const optionsParts = []
      if (optWritable) optionsParts.push('allwrite')
      else optionsParts.push('noallwrite')
      
      if (optCompress) optionsParts.push('compress')
      else optionsParts.push('nocompress')
      
      if (optRmdir) optionsParts.push('rmdir')
      else optionsParts.push('normdir')
      
      // Standardize other options usually desired
      optionsParts.push('noclobber')
      optionsParts.push('unlocked')
      optionsParts.push('nomodtime')
      
      // if (optBackup) optionsParts.push('backup')

      const optionsStr = optionsParts.join(' ')

      const result = await window.p4.createClient({
        name: newName,
        root: newRoot,
        options: optionsStr,
        submitOptions: submitOption,
        stream: selectedStream?.stream, // Use selected stream path
        description: description
      })

      if (result.success) {
        // Auto-sync after creation
        try {
          // 1. Switch to new client
          await window.p4.setClient(newName)
          
          // 2. Sync files (Get Latest)
          // We need to show "Syncing..." state
          // Since we are inside handleCreate which sets isCreating=true,
          // let's update a status message if we had one, or just assume "Creating..." covers it?
          // Better to use a specific toast or just do it.
          // Since ClientSelector unmounts when onClientSelected is called, 
          // we should do the sync HERE before unmounting.
          
          // Note: We can't easily change the button text from here without new state, 
          // but "Creating..." is acceptable or we can add state.
          
          await window.p4.sync()
          
          // 3. Complete
          await loadClients()
          setCreateMode(false)
          
          // 4. Select and enter
          onClientSelected(newName)
        } catch (syncErr: any) {
           setError(`Workspace created but sync failed: ${syncErr.message}`)
           setIsCreating(false)
           // Do not close create mode so user sees error
        }
      } else {
        setError(result.message)
        setIsCreating(false)
      }
    } catch (err: any) {
      setError(err.message)
      setIsCreating(false)
    }
  }

  if (loading && !isCreateMode) {
    return (
      <div className="h-screen bg-p4-dark flex items-center justify-center">
        <div className="text-center">
          <SquidIcon className="w-20 h-20 mx-auto mb-4 animate-doom-chit" />
          <div className="text-xl text-gray-300 mb-2">Loading workspaces...</div>
          <div className="text-sm text-gray-500">Please wait</div>
        </div>
      </div>
    )
  }

  // Create Mode View
  if (isCreateMode) {
    const filteredStreams = streams
      .map(s => {
         const leafName = s.stream.split('/').pop() || s.stream
         return { ...s, leafName }
      })
      .filter(s => 
        s.leafName.toLowerCase().includes(streamSearch.toLowerCase()) || 
        s.name.toLowerCase().includes(streamSearch.toLowerCase()) ||
        s.stream.toLowerCase().includes(streamSearch.toLowerCase())
      )
      .sort((a, b) => a.leafName.localeCompare(b.leafName))

    return (
      <div className="h-screen bg-p4-dark flex items-center justify-center overflow-auto py-8">
        <div className="w-[700px] bg-p4-darker border border-p4-border rounded-lg shadow-xl flex flex-col max-h-full">
          <div className="p-6 border-b border-p4-border">
            <h2 className="text-xl font-bold text-white">New Workspace</h2>
            <p className="text-sm text-gray-400 mt-1">Configure your new Perforce workspace</p>
          </div>

          <div className="p-6 space-y-6 overflow-y-auto custom-scrollbar">
            {error && (
              <div className="bg-red-900/20 border border-red-500/50 text-red-200 p-3 rounded text-sm">
                {error}
              </div>
            )}

            {/* Source Stream Selection */}
            <div className="bg-gray-800/30 p-4 rounded border border-gray-700/50 space-y-4">
               <h3 className="text-sm font-medium text-p4-blue uppercase tracking-wider mb-2">1. Source Stream</h3>
               <div className="grid grid-cols-2 gap-4">
                  <div>
                    <label className="block text-sm font-medium text-gray-400 mb-1">Depot</label>
                    <select
                      value={selectedDepot}
                      onChange={(e) => handleDepotChange(e.target.value)}
                      className="w-full bg-p4-dark border border-p4-border rounded px-3 py-2 text-white focus:outline-none focus:border-p4-blue"
                    >
                      <option value="">Select Depot</option>
                      {depots.map(d => (
                        <option key={d.depot} value={d.depot}>{d.depot} ({d.type})</option>
                      ))}
                    </select>
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-gray-400 mb-1 flex items-center justify-between">
                      <span>Stream</span>
                      {loadingStreams && (
                        <span className="flex items-center text-xs text-p4-blue">
                          <svg className="animate-spin -ml-1 mr-2 h-3 w-3 text-p4-blue" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                            <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                            <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                          </svg>
                          Loading...
                        </span>
                      )}
                    </label>
                    <div className="space-y-2">
                       <input
                        type="text"
                        value={streamSearch}
                        onChange={(e) => setStreamSearch(e.target.value)}
                        placeholder="Search workspace or stream..."
                        disabled={!selectedDepot || loadingStreams}
                        className="w-full bg-p4-dark border border-p4-border rounded px-3 py-1.5 text-sm text-white focus:outline-none focus:border-p4-blue disabled:opacity-50"
                      />
                      <select
                        value={selectedStream?.stream || ''}
                        onChange={(e) => {
                          const s = streams.find(st => st.stream === e.target.value) || null
                          setSelectedStream(s)
                        }}
                        disabled={!selectedDepot || loadingStreams}
                        className={`w-full bg-p4-dark border border-p4-border rounded px-3 py-2 text-white focus:outline-none focus:border-p4-blue disabled:opacity-50 disabled:cursor-not-allowed transition-opacity ${loadingStreams ? 'opacity-50' : ''}`}
                      >
                        <option value="">{loadingStreams ? 'Loading streams...' : 'Select Stream'}</option>
                        {filteredStreams.map(s => {
                          const label = s.leafName !== s.name 
                            ? `${s.leafName} (${s.name})`
                            : s.leafName
                          return (
                            <option key={s.stream} value={s.stream} title={s.description}>{label}</option>
                          )
                        })}
                      </select>
                    </div>
                  </div>
               </div>
            </div>

            {/* Naming Convention */}
            <div className="bg-gray-800/30 p-4 rounded border border-gray-700/50 space-y-4">
               <h3 className="text-sm font-medium text-p4-blue uppercase tracking-wider mb-2">2. Naming Convention</h3>
               <div className="grid grid-cols-2 gap-4">
                  <div>
                    <label className="block text-sm font-medium text-gray-400 mb-1">Prefix</label>
                    <input
                      type="text"
                      value={prefix}
                      onChange={(e) => setPrefix(e.target.value)}
                      className="w-full bg-p4-dark border border-p4-border rounded px-3 py-2 text-white focus:outline-none focus:border-p4-blue"
                      placeholder="e.g. hoh_haein"
                    />
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-gray-400 mb-1">Root Base Directory</label>
                    <input
                      type="text"
                      value={rootBase}
                      onChange={(e) => setRootBase(e.target.value)}
                      className="w-full bg-p4-dark border border-p4-border rounded px-3 py-2 text-white focus:outline-none focus:border-p4-blue"
                      placeholder="e.g. C:\Perforce"
                    />
                  </div>
               </div>
            </div>

            {/* Generated Info */}
            <div className="space-y-4 pt-2">
              <div>
                <label className="block text-sm font-medium text-gray-400 mb-1">Workspace Name (Auto-generated)</label>
                <input
                  type="text"
                  value={newName}
                  onChange={handleNameChange}
                  className="w-full bg-p4-dark border border-p4-border rounded px-3 py-2 text-white focus:outline-none focus:border-p4-blue"
                  placeholder="Select a stream to generate name"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-400 mb-1">Root Directory (Auto-generated)</label>
                <div className="flex gap-2">
                  <input
                    type="text"
                    value={newRoot}
                    onChange={(e) => setNewRoot(e.target.value)}
                    className="flex-1 bg-p4-dark border border-p4-border rounded px-3 py-2 text-white focus:outline-none focus:border-p4-blue"
                    placeholder="Select a stream to generate root"
                  />
                  <button
                    onClick={handleBrowseRoot}
                    className="px-3 py-2 bg-gray-700 hover:bg-gray-600 rounded text-sm text-white transition-colors whitespace-nowrap"
                  >
                    Browse...
                  </button>
                </div>
              </div>
            </div>

            {/* File Options */}
            <div>
              <h3 className="text-sm font-medium text-gray-300 mb-3 border-b border-gray-700 pb-1">3. Options</h3>
              <div className="grid grid-cols-2 gap-4">
                <label className="flex items-center space-x-2 cursor-pointer">
                  <input
                    type="checkbox"
                    checked={optCompress}
                    onChange={(e) => setOptCompress(e.target.checked)}
                    className="rounded border-gray-600 bg-gray-700 text-p4-blue focus:ring-0"
                  />
                  <span className="text-sm text-gray-300">Compress</span>
                </label>

                <label className="flex items-center space-x-2 cursor-pointer">
                  <input
                    type="checkbox"
                    checked={optRmdir}
                    onChange={(e) => setOptRmdir(e.target.checked)}
                    className="rounded border-gray-600 bg-gray-700 text-p4-blue focus:ring-0"
                  />
                  <span className="text-sm text-gray-300">Rmdir</span>
                </label>

                <label className="flex items-center space-x-2 cursor-pointer">
                  <input
                    type="checkbox"
                    checked={optBackup}
                    onChange={(e) => setOptBackup(e.target.checked)}
                    className="rounded border-gray-600 bg-gray-700 text-p4-blue focus:ring-0"
                  />
                  <span className="text-sm text-gray-300">Backup enable</span>
                </label>
              </div>
            </div>

            {/* Client Type */}
            <div>
              <h3 className="text-sm font-medium text-gray-300 mb-2">Client Type</h3>
              <div className="flex gap-4">
                <label className="flex items-center space-x-2 cursor-pointer">
                  <input
                    type="radio"
                    checked={optWritable}
                    onChange={() => setOptWritable(true)}
                    className="border-gray-600 bg-gray-700 text-p4-blue focus:ring-0"
                  />
                  <span className="text-sm text-gray-300">Writable</span>
                </label>
                <label className="flex items-center space-x-2 cursor-pointer">
                  <input
                    type="radio"
                    checked={!optWritable}
                    onChange={() => setOptWritable(false)}
                    className="border-gray-600 bg-gray-700 text-p4-blue focus:ring-0"
                  />
                  <span className="text-sm text-gray-300">Read-only</span>
                </label>
              </div>
            </div>

            {/* On Submit */}
            <div>
              <label className="block text-sm font-medium text-gray-400 mb-1">On submit</label>
              <select
                value={submitOption}
                onChange={(e) => setSubmitOption(e.target.value)}
                className="w-full bg-p4-dark border border-p4-border rounded px-3 py-2 text-white focus:outline-none focus:border-p4-blue"
              >
                <option value="submitunchanged">Submit all selected files</option>
                <option value="revertunchanged">Revert unchanged files</option>
                <option value="leaveunchanged">Leave unchanged files</option>
              </select>
            </div>

             {/* Description */}
             <div>
                <label className="block text-sm font-medium text-gray-400 mb-1">Description</label>
                <textarea
                  value={description}
                  onChange={(e) => setDescription(e.target.value)}
                  className="w-full h-20 bg-p4-dark border border-p4-border rounded px-3 py-2 text-white focus:outline-none focus:border-p4-blue resize-none"
                  placeholder="Optional description..."
                />
              </div>

          </div>

          <div className="p-6 border-t border-p4-border flex justify-end gap-3 bg-p4-darker">
            <button
              onClick={() => setCreateMode(false)}
              className="px-4 py-2 bg-gray-700 hover:bg-gray-600 rounded text-sm transition-colors text-white"
            >
              Cancel
            </button>
            <button
              onClick={handleCreate}
              disabled={isCreating}
              className="px-4 py-2 bg-p4-blue hover:bg-blue-600 rounded text-sm transition-colors text-white disabled:opacity-50"
            >
              {isCreating ? 'Creating & Syncing...' : 'Create Workspace'}
            </button>
          </div>
        </div>
      </div>
    )
  }

  if (error && !clients.length) {
    return (
      <div className="h-screen bg-p4-dark flex items-center justify-center">
        <div className="text-center max-w-md">
          <div className="text-xl text-red-400 mb-2">Error Loading Workspaces</div>
          <div className="text-sm text-gray-400 mb-4">{error}</div>
          <button
            onClick={loadClients}
            className="px-4 py-2 bg-p4-blue hover:bg-blue-600 rounded text-sm transition-colors text-white"
          >
            Retry
          </button>
        </div>
      </div>
    )
  }

  // List View
  return (
    <div className="h-screen bg-p4-dark flex items-center justify-center">
      <div className="w-[500px]">
        <div className="text-center mb-8">
          <h1 className="text-2xl font-bold text-white mb-2">PerforceSquid</h1>
          <p className="text-gray-400">Select a workspace to continue</p>
        </div>

        <div className="bg-p4-darker border border-p4-border rounded-lg overflow-hidden flex flex-col max-h-[60vh]">
          {clients.length === 0 ? (
             <div className="p-8 text-center text-gray-500">
                No workspaces found.
             </div>
          ) : (
            <div className="overflow-y-auto custom-scrollbar">
                {clients.map((client) => (
                    <div
                    key={client.name}
                    onClick={() => selectClient(client.name)}
                    className="p-4 border-b border-p4-border last:border-b-0 cursor-pointer hover:bg-gray-800 transition-colors group"
                    >
                    <div className="flex items-center justify-between">
                        <div className="flex-1 min-w-0">
                        <div className="text-sm font-medium text-gray-200 group-hover:text-white">{client.name}</div>
                        <div className="text-xs text-gray-500 truncate mt-1">{client.root}</div>
                        </div>
                        <span className="text-gray-600 text-xl ml-4 group-hover:text-p4-blue group-hover:translate-x-1 transition-all">→</span>
                    </div>
                    </div>
                ))}
            </div>
          )}
          
          <div className="p-4 bg-gray-800/50 border-t border-p4-border">
            <button
              onClick={() => {
                setCreateMode(true)
                setNewName('')
                setNewRoot('')
                setError(null)
              }}
              className="w-full py-2 border border-dashed border-gray-600 text-gray-400 hover:border-p4-blue hover:text-p4-blue rounded transition-colors flex items-center justify-center gap-2"
            >
              <span className="text-lg">+</span> New Workspace
            </button>
          </div>
        </div>
      </div>
    </div>
  )
}
